language: clojure
lein: lein2
before_script: wget http://travis.xscheme.de/thrift-0.9.0-ubuntu-12.04-i386; chmod u+x thrift-0.9.0-ubuntu-12.04-i386; ./thrift-0.9.0-ubuntu-12.04-i386
script: lein2 midje
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
