language: clojure
lein: lein2
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift 
install: lein2 with-profile dev,test-all deps
script: lein2 midje-all
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
